# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            MF's blog
tagline:          ''
description:      ''
url:              https://mflak.eu
baseurl:          /
picture: assets/images/profile.jpg

author:
  name:           'Michał Flak'
  url:            https://twitter.com/mflakdev

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/elo-siema

twitter: https://twitter.com/mflakdev
# instagram: myinstagram
# pinterest: mypinterest
linkedin: https://linkedin.com/in/mflak
# youtube: myyoutube
# spotify: myspotify
github: https://github.com/elo-siema
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: michal@mflak.eu

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mflak-eu # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories


plugins:
  - jekyll-paginate